# 2-12. 프로젝트 (2) load_wine : 와인을 분류해 봅시다

이번에는 와인 데이터입니다. 와인의 어떤 특징으로 와인의 종류를 분류해 볼 수 있을까요?

데이터에 어떤 정보가 담겨있는지, feature는 무엇이고 label은 무엇인지 확인해 보면서 진행하는 점, 잊지마세요!

## (1) 필요한 모듈 import하기

In [1]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

## (2) 데이터 준비


load_wine 메서드를 사용합니다.

In [5]:
from sklearn.datasets import load_wine

wine = load_wine()

wine.keys()
# wine 데이터에 어떤 정보들이 담겨 있는지 확인

wine_data = wine.data
print (wine_data.shape)

(178, 13)


## (3) 데이터 이해하기

지피지기면 백전불태! 다루어야 할 데이터를 자세히 살펴봅시다.

Feature Data 지정하기
Label Data 지정하기
Target Names 출력해 보기
데이터 Describe 해 보기

In [6]:
# Feature Data 지정하기
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [7]:
# label Data 지정하기
wine_label = wine.target
print (wine_label.shape)
wine_label

(178,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [8]:
# Target Names 출력
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
# Data Describe
print (wine.DESCR)

## (4) train, test 데이터 분리

모델 학습과 테스트용 문제지와 정답지를 준비해 봅시다.
X_train, X_test, y_train, y_test를 생성하는 방법을 참고해 보세요.

In [11]:
# Pandas data 가져오기
import pandas as pd
print (pd.__version__)

wine_df = pd.DataFrame(data=wine_data, columns=wine.feature_names)
wine_df

# Label 칼럼 추가
wine_df["label"] = wine.target
wine_df

1.1.5


alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  label  
0                            3.92   1065.0      0  
1                            3.40   1050.0      0  
2                            3.17   1185.0      0  
3                            3.45   1480.0      0  
4                            2.93    735.0      0  
..                            ...      ...    ...  
173                          1.74    740.0      2  
174                          1.56    750.0      2  
175                          1.56    835.0      2  
176                          1.62    840.0      2  
177                          1.60    560.0      2  

[178 rows x 14 columns]

In [12]:
# train, test 데이터 분리
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(wine_data, 
                                                    wine_label, 
                                                    test_size=0.2, 
                                                    random_state=7)

print('X_train 개수: ', len(X_train), ', X_test 개수: ', len(X_test))

X_train.shape, y_train.shape

X_test.shape, y_test.shape

X_train 개수:  142 , X_test 개수:  36


((36, 13), (36,))

In [13]:
y_train, y_test

(array([2, 2, 0, 2, 0, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
        2, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 0, 0, 2, 0, 2, 1, 1, 2, 1, 0,
        1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 2, 0, 1, 0, 2, 1, 0, 0, 0,
        0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 1, 2, 1, 1,
        0, 0, 2, 0, 2, 2, 2, 1, 2, 1, 2, 1, 0, 0, 2, 1, 2, 1, 1, 0, 1, 2,
        1, 2, 0, 0, 2, 0, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1, 2, 0, 1,
        1, 1, 0, 2, 1, 1, 2, 1, 0, 2]),
 array([2, 0, 2, 2, 1, 2, 1, 0, 1, 2, 0, 1, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1,
        1, 1, 0, 2, 1, 2, 2, 2, 1, 0, 2, 1, 1, 1]))

## (5) 다양한 모델로 학습시켜보기

학습데이터 X_train, y_train 을 활용해 분류기 모델을 만들어 봅시다. 어떤 모델이 가장 좋은 성능을 보일까요?

Decision Tree 사용해 보기
Random Forest 사용해 보기
SVM 사용해 보기
SGD Classifier 사용해 보기
Logistic Regression 사용해 보기

### 의사결정나무 사용

In [14]:
## 의사결정나무 가져오기
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(random_state=32)
print(decision_tree._estimator_type)

classifier


In [15]:
# Training set에 fitting하기
decision_tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=32)

In [16]:
# 모델 학습 및 예측
decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.89      1.00      0.94        17
           2       1.00      0.83      0.91        12

    accuracy                           0.94        36
   macro avg       0.96      0.94      0.95        36
weighted avg       0.95      0.94      0.94        36



In [17]:
# accuracy 측정
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9444444444444444

In [18]:
# 와인 데이터 가져오기
from sklearn.datasets import load_wine

wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [23]:
wine_data[0]

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

In [61]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.imshow(wine.data[0].reshape(8, 8), cmap='gray')
plt.axis('off')
plt.show()

# size가 안맞는건지 배열이 안맞는건지 reshape 에러가 발생한다.

ValueError: cannot reshape array of size 13 into shape (8,8)

In [ ]:
# New label로 다시 학습시키기
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                                    wine,
                                                    test_size=0.2,
                                                    random_state=32)

decision_tree = DecisionTreeClassifier(random_state=32)
decision_tree.fit(X_train, y_train)
y_pred = decision_tree.predict(X_test)


accuracy = accuracy_score(y_test, y_pred)
accuracy


In [42]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[ 7,  0,  0],
       [ 0, 17,  0],
       [ 0,  2, 10]])

In [35]:
confusion_matrix(y_test, fake_pred)

array([[ 7,  0,  0],
       [17,  0,  0],
       [12,  0,  0]])

In [36]:
# Precision, Recall, f1 score 확인해보기
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.89      1.00      0.94        17
           2       1.00      0.83      0.91        12

    accuracy                           0.94        36
   macro avg       0.96      0.94      0.95        36
weighted avg       0.95      0.94      0.94        36



In [37]:
print(classification_report(y_test, fake_pred))

              precision    recall  f1-score   support

           0       0.19      1.00      0.33         7
           1       0.00      0.00      0.00        17
           2       0.00      0.00      0.00        12

    accuracy                           0.19        36
   macro avg       0.06      0.33      0.11        36
weighted avg       0.04      0.19      0.06        36



/home/aiffel/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [38]:
# 정확도 측정하기
accuracy_score(y_test, y_pred), accuracy_score(y_test, fake_pred)

(0.9444444444444444, 0.19444444444444445)

### Random Forest 사용

In [44]:
# Random Forest 가져오기
from sklearn.ensemble import RandomForestClassifier

In [45]:
# train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                    wine_label,
                                    test_size = 0.2,
                                    random_state = 32)

# 모델 학습 및 예측
random_forest = RandomForestClassifier(random_state = 32)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        36
   macro avg       0.97      0.97      0.97        36
weighted avg       0.97      0.97      0.97        36



In [46]:
# accuracy 측정
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9722222222222222

### SVM 사용

In [47]:
# SVM 가져오기
from sklearn import svm
svm_model = svm.SVC()

In [48]:
# train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                    wine_label,
                                    test_size = 0.2,
                                    random_state = 32)
# 모델 학습 및 예측
svm_model.fit(X_train, y_train)
y_pred = svm_model.predict(X_test)

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.81      0.87        16
           1       0.41      0.90      0.56        10
           2       0.00      0.00      0.00        10

    accuracy                           0.61        36
   macro avg       0.45      0.57      0.48        36
weighted avg       0.53      0.61      0.54        36



/home/aiffel/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [49]:
# accuracy 측정
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.6111111111111112

### SGD Classifier 사용

In [50]:
# SGD Classifier 가져오기
from sklearn.linear_model import SGDClassifier
sgd_model = SGDClassifier()

In [51]:
# train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                    wine_label,
                                    test_size = 0.2,
                                    random_state = 32)

# 모델 학습 및 예측
sgd_model.fit(X_train, y_train)
y_pred = sgd_model.predict(X_test)

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.55      1.00      0.71        16
           1       0.00      0.00      0.00        10
           2       0.14      0.10      0.12        10

    accuracy                           0.47        36
   macro avg       0.23      0.37      0.28        36
weighted avg       0.28      0.47      0.35        36



/home/aiffel/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [52]:
# accuracy 측정
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.4722222222222222

### Logistic Regression 사용

In [53]:
# Logistic Regression 가져오기
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()

In [56]:
# train, test 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(wine_data,
                                    wine_label,
                                    test_size = 0.2,
                                    random_state = 32)

# 모델 학습 및 예측
logistic_model.fit(X_train, y_train)
y_pred = logistic_model.predict(X_test)

print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97        16
           1       0.89      0.80      0.84        10
           2       0.90      0.90      0.90        10

    accuracy                           0.92        36
   macro avg       0.91      0.90      0.90        36
weighted avg       0.92      0.92      0.91        36



/home/aiffel/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [57]:
# accuracy 측정
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9166666666666666

## (6) 모델을 평가해 보기

학습된 모델들의 테스트데이터 예측 결과를 어떻게 해석해야 할까요? 모델의 성능을 평가하는 지표로는 무엇이 좋을까요? sklearn.metrics 에서 제공하는 평가지표 중 적절한 것을 선택해 보세요. 선택하신 이유도 설명해 주세요.

Wine 데이터셋 역시 다양한 모델로 학습을 시켰는데
이번에는 손글씨 데이터와는 다르게 SVM, SGD 모델에서는 정확도가 많이 떨어진 것을 확인할 수
있었다. 손글씨 데이터를 학습시켜 볼 때에는 모델별로 정확도 차이가 없어서
모델을 평가하기가 조금 애매했는데 Wine 데이터셋을 학습 시킬 때는 모델 간의 차이가
있어서 모델을 선정하기가 조금 수월해 진 것 같다.
물론 정확도만으로 데이터 학습 모델을 선정하기에는 무리가 있지만 적어도
이번 데이터셋을 분류할 때에는 SVM, SGD 모델이 좋은 성능을 보여주지 못한 것 같다.